'use client';

import { useEffect, useRef, useState } from 'react';
import { Home, Package, Wallet, UserRound, Bell, Plus, Search, ChevronRight, ArrowLeft, MapPin, Navigation, Bike, Truck, Zap, Check, CheckCheck, ShieldCheck, Route, Clock3, Copy, Send, Leaf, Download, SlidersHorizontal, MessageCircle, Settings2, Bookmark, HelpCircle, X, CircleCheck, Minus, LogOut, Play, Pause, RotateCcw, CreditCard, ReceiptText, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { Switch } from '@/components/ui/switch';
import { Message, MessageContent } from '@/components/ui/message';
import { Bubble, BubbleContent } from '@/components/ui/bubble';
import { MessageScrollerProvider, MessageScroller, MessageScrollerContent, MessageScrollerViewport } from '@/components/ui/message-scroller';
import { toast } from 'sonner';
import { PaymentReceipt } from '@/components/payment-receipt';
import { recordPreviewPayment, paymentMethodLabel, type Transaction, type PaymentRequest, type PaymentMethod } from '@/lib/payments';
import { cn } from '@/lib/utils';
import { initialShipments, restorePreview, nextShipmentId, isShipment, money, servicePrice, draftFromText, assistantReply, type Shipment, type BookingDraft } from '@/lib/relay';

type View = 'home' | 'shipments' | 'assistant' | 'wallet' | 'profile' | 'tracking' | 'booking';
const tabs = [{ id: 'home', label: 'Home', icon: Home }, { id: 'shipments', label: 'Shipments', icon: Package }, { id: 'assistant', label: 'Relay AI', icon: RelayAIMark }, { id: 'wallet', label: 'Wallet', icon: Wallet }, { id: 'profile', label: 'Account', icon: UserRound }] as const;
const blankDraft: BookingDraft = { from: '', to: '', recipient: '', phone: '', item: '', weight: 1, service: 'standard', when: 'Today', date: '', instructions: '' };

function RelayAIMark({size = 24}: {size?: number}) {
  return <svg width={size} height={size} viewBox="0 0 32 32" fill="none" aria-hidden="true" className="relay-ai-symbol"><path d="M8 24V12a6 6 0 0 1 6-6h4a6 6 0 0 1 0 12h-4" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/><path d="m17 18 7 8" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/><circle cx="8" cy="25" r="3" fill="#f6a24d"/><circle cx="24" cy="7" r="2.5" fill="#f6a24d"/></svg>;
}

function RouteMap({ compact = false }: { compact?: boolean; progress?: number }) {
  const [zoom, setZoom] = useState(1);
  const [playing, setPlaying] = useState(false);
  const [position, setPosition] = useState(0);
  useEffect(() => {
    if (!playing || position >= 100) return;
    const timer = setInterval(() => setPosition(prev => Math.min(prev + 2, 100)), 400);
    return () => clearInterval(timer);
  }, [playing, position]);
  const points = [[48, 231], [112, 231], [112, 159], [203, 159], [203, 117], [261, 117], [261, 78]];
  const lengths = points.slice(1).map((p, i) => Math.hypot(p[0] - points[i][0], p[1] - points[i][1]));
  let distance = lengths.reduce((a, b) => a + b, 0) * position / 100;
  let rider = points[points.length - 1];
  for (let i = 0; i < lengths.length; i++) { if (distance <= lengths[i]) { const ratio = distance / lengths[i]; rider = [points[i][0] + (points[i + 1][0] - points[i][0]) * ratio, points[i][1] + (points[i + 1][1] - points[i][1]) * ratio]; break; } distance -= lengths[i]; }
  return <div className={cn('preview-map-block', compact && 'compact')}><div className="route-map">
    <div className="preview-map-canvas" style={{ transform: `scale(${zoom})` }}>
    {/* eslint-disable-next-line @next/next/no-img-element */}
    <img src="/art/city.webp" alt=""/>
    <svg className="preview-route-overlay" viewBox="0 0 400 300" preserveAspectRatio="none" role="img" aria-label="Preview map: a simulated courier route from pickup to destination. This is not live GPS."><polyline points="48,231 112,231 112,159 203,159 203,117 261,117 261,78" fill="none" stroke="white" strokeWidth="9" strokeLinejoin="round"/><polyline points="48,231 112,231 112,159 203,159 203,117 261,117 261,78" fill="none" stroke="#bd621d" strokeWidth="4" strokeLinejoin="round"/><circle cx="48" cy="231" r="6" fill="#fff" stroke="#9c4b0b" strokeWidth="3"/><circle cx="261" cy="78" r="7" fill="#f9ac5e" stroke="#fff" strokeWidth="3"/><g className="route-courier" style={{transform:`translate(${rider[0]}px, ${rider[1]}px)`, transitionDuration: playing && position > 0 ? undefined : '0ms'}}><circle r="13" fill="#2d302a" stroke="#fff" strokeWidth="3"/><path d="M-5 5 0-6 5 5 0 2Z" fill="#ffb86c"/></g></svg></div>
    <span className="map-label">PREVIEW MAP · No live GPS</span>
    {!compact && <div className="map-controls"><Button size="icon" variant="outline" disabled={zoom >= 1.8} aria-label="Zoom in" onClick={() => setZoom(Math.min(zoom + .2, 1.8))}><Plus aria-hidden="true"/></Button><Button size="icon" variant="outline" disabled={zoom <= 1} aria-label="Zoom out" onClick={() => setZoom(Math.max(zoom - .2, 1))}><Minus aria-hidden="true"/></Button></div>}
  </div>{!compact && <div className="preview-map-toolbar"><Button variant="outline" onClick={() => { if (position >= 100) setPosition(0); setPlaying(!playing || position >= 100); }} aria-label={playing && position < 100 ? 'Pause preview route' : 'Play preview route'}>{playing && position < 100 ? <Pause aria-hidden="true" size={15}/> : <Play aria-hidden="true" size={15}/>}{playing && position < 100 ? 'Pause preview' : position >= 100 ? 'Replay route' : 'Play preview route'}</Button><span className="preview-map-status" role="status" aria-live="polite">{position >= 100 ? 'Preview arrival complete' : playing ? 'Simulating delivery' : position > 0 ? 'Simulation paused' : 'Try a sample journey'}</span><Button size="icon" variant="ghost" aria-label="Reset preview route" onClick={() => { setPlaying(false); setPosition(0); }}><RotateCcw aria-hidden="true" size={16}/></Button></div>}</div>;
}

function Artwork({ kind, className = '' }: {kind: 'ship' | 'parcels'; className?: string}) {
  // eslint-disable-next-line @next/next/no-img-element
  return <img className={className} src={`/art/${kind}.webp`} alt=""/>;
}
function ParcelProgress({progress}: {progress: number}) {
  return <ol className="parcel-progress" aria-label="Shipment progress">{['Booked', 'Picked up', 'On the way', 'Delivered'].map((label, i) => <li key={label} className={i <= progress ? 'complete' : ''} aria-current={i === progress ? 'step' : undefined}><span>{i <= progress ? <Check aria-hidden="true" size={12}/> : <span/>}</span><small>{label}</small></li>)}</ol>;
}

function ShipmentRow({ shipment, onClick }: { shipment: Shipment; onClick: () => void }) {
  return <button className="shipment-row" aria-label={`View ${shipment.item}, ${shipment.id}, ${shipment.status}`} onClick={onClick}><span className="parcel-icon"><Truck aria-hidden="true" size={21}/></span><span className="shipment-info"><small>Tracking number</small><strong>{shipment.id}</strong><span><MapPin aria-hidden="true" size={12}/>{shipment.from.split(',')[0]} <span aria-hidden="true">→</span> {shipment.to.split(',')[0]}</span></span><span className="shipment-end"><Badge variant="secondary" className={cn('status-badge', shipment.status === 'Delivered' && 'done')}>{shipment.status}</Badge><ChevronRight aria-hidden="true" size={20}/></span></button>;
}

function OriginalVideo({src, poster, className}: {src: string; poster?: string; className?: string}) {
  const video = useRef<HTMLVideoElement>(null);
  useEffect(() => {
    const preference = window.matchMedia('(prefers-reduced-motion: reduce)');
    const apply = () => {
      const element = video.current;
      if (!element) return;
      if (preference.matches) element.pause();
      else void element.play().catch(() => { /* Poster remains available if autoplay is blocked. */ });
    };
    apply(); preference.addEventListener('change', apply);
    return () => preference.removeEventListener('change', apply);
  }, []);
  return <video ref={video} className={className} src={src} poster={poster} muted loop playsInline preload="auto" aria-hidden="true"/>;
}

export default function App() {
  const [view, setView] = useState<View>('home');
  const [onboarding, setOnboarding] = useState(true);
  const [signIn, setSignIn] = useState(false);
  const [signingIn, setSigningIn] = useState(false);
  const [signInError, setSignInError] = useState('');
  const [liveDetails, setLiveDetails] = useState(false);
  const [shipments, setShipments] = useState<Shipment[]>(initialShipments);
  const [selected, setSelected] = useState(initialShipments[0]);
  const [balance, setBalance] = useState(24500);
  const [transactions, setTransactions] = useState<Transaction[]>([{ id: 't1', title: 'Wallet top-up', amount: 20000, date: 'Today, 9:12 am' }, { id: 't2', title: 'Delivery · RLY-20841', amount: -3500, date: 'Today, 8:45 am' }, { id: 't3', title: 'Delivery · RLY-20839', amount: -2000, date: 'Yesterday, 2:10 pm' }]);
  const [ready, setReady] = useState(false);
  const [draft, setDraft] = useState<BookingDraft>(blankDraft);
  const [step, setStep] = useState(1);
  const [bookingError, setBookingError] = useState('');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [modal, setModal] = useState<string | null>(null);
  const [topup, setTopup] = useState('10000');
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('wallet');
  const [pendingPayment, setPendingPayment] = useState<(PaymentRequest & {draft?:BookingDraft}) | null>(null);
  const [activeReceipt, setActiveReceipt] = useState<Transaction | null>(null);
  const paymentCommitted = useRef(false);
  const [chat, setChat] = useState([{ role: 'assistant', text: "Welcome to Relay’s preview AI. I can check your sample shipments, estimate delivery costs, summarize your deliveries, and prepare editable booking drafts. Try a prompt below or tell me what you want to send." }]);
  const [message, setMessage] = useState('');
  const [pendingDraft, setPendingDraft] = useState<BookingDraft | null>(null);
  const [notify, setNotify] = useState(true);
  const [name, setName] = useState('Tosin Omowumi');
  const [profileName, setProfileName] = useState('');
  const [profileError, setProfileError] = useState('');
  const [addressError, setAddressError] = useState('');
  const [savedAddresses, setSavedAddresses] = useState([{ label: 'Home', address: '12 Admiralty Way, Lekki Phase 1, Lagos' }, { label: 'Office', address: '24 Akin Adesola Street, Victoria Island, Lagos' }]);
  const [newAddress, setNewAddress] = useState('');
  const [addressLabel, setAddressLabel] = useState('');
  const [riderMessages, setRiderMessages] = useState<string[]>([]);
  const [riderMessage, setRiderMessage] = useState('');
  const [zoomText, setZoomText] = useState(false);
  const [trackingInput, setTrackingInput] = useState('');
  const [announcement, setAnnouncement] = useState('');
  const [invalidField, setInvalidField] = useState<string | null>(null);
  const dialogReturnFocus = useRef<HTMLElement | null>(null);
  const firstRender = useRef(true);
  const previousModal = useRef<string | null>(null);
  useEffect(() => {
    const root = document.documentElement;
    const pointer = () => { root.dataset.relayInput = 'pointer'; };
    const keyboard = () => { root.dataset.relayInput = 'keyboard'; };
    document.addEventListener('pointerdown', pointer, {passive:true});
    document.addEventListener('keydown', keyboard);
    return () => { document.removeEventListener('pointerdown', pointer); document.removeEventListener('keydown', keyboard); delete root.dataset.relayInput; };
  }, []);
  const signInRequest = useRef<AbortController | null>(null);
  useEffect(() => () => signInRequest.current?.abort(), []);
  const openModal = (next: string) => {
    if (!modal) dialogReturnFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    if (next === 'edit-profile') { setProfileName(name); setProfileError(''); }
    if (next === 'addresses') setAddressError('');
    setModal(next);
  };
  useEffect(() => {
    const changedStage = modal && previousModal.current && modal !== previousModal.current;
    previousModal.current = modal;
    if (!changedStage) return;
    const frame = requestAnimationFrame(() => document.getElementById('relay-dialog-title')?.focus());
    return () => cancelAnimationFrame(frame);
  }, [modal]);
  const failBooking = (field: string, error: string) => { setInvalidField(field); setBookingError(error); document.getElementById(field)?.focus(); };
  useEffect(() => {
    if (firstRender.current) { firstRender.current = false; return; }
    if (document.querySelector('[data-slot="dialog-content"]')) return;
    document.getElementById(signIn ? 'sign-in-title' : view === 'booking' ? 'booking-heading' : 'page-title')?.focus();
  }, [view, step, onboarding, signIn, signingIn]);

  useEffect(() => {
    const hydration = requestAnimationFrame(() => {
    try { const stored = localStorage.getItem('relay-v1'); if (stored) { const data = JSON.parse(stored); const restored = restorePreview(data, { shipments: initialShipments, balance: 24500, transactions, name, addresses: savedAddresses, notify: true, largerText: false }); setShipments(restored.shipments); setBalance(restored.balance); setTransactions(restored.transactions); setName(restored.name); setSavedAddresses(restored.addresses); setNotify(restored.notify); setZoomText(restored.largerText); } } catch { toast.error('Saved preview could not be loaded. Starting with sample deliveries.'); }
    setReady(true);
    });
    return () => cancelAnimationFrame(hydration);
  // Initial browser-only hydration.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { if (ready) { try { localStorage.setItem('relay-v1', JSON.stringify({ shipments, balance, transactions, name, addresses: savedAddresses, notify, largerText: zoomText })); } catch { toast.error('Your browser could not save these changes. Keep this tab open to retain your changes.', { id: 'storage-unavailable' }); } } }, [ready, shipments, balance, transactions, name, savedAddresses, notify, zoomText]);
  const go = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: 'instant' }); };
  const track = (shipment: Shipment) => { setSelected(shipment); setLiveDetails(false); go('tracking'); };
  const startBooking = (prefill?: BookingDraft) => { setPaymentMethod('wallet'); setDraft(prefill ?? { ...blankDraft }); setStep(1); setBookingError(''); setInvalidField(null); go('booking'); };
  const updateDraft = (key: keyof BookingDraft, value: string | number) => setDraft(prev => ({ ...prev, [key]: value }));
  const active = shipments.filter(s => s.status !== 'Delivered');
  const visibleShipments = shipments.filter(s => (filter === 'all' || (filter === 'active' ? s.status !== 'Delivered' : s.status === 'Delivered')) && `${s.id} ${s.item} ${s.from} ${s.to}`.toLowerCase().includes(query.toLowerCase()));
  const price = servicePrice(draft.service, draft.weight);
  const receipt = (shipment: Shipment) => {
    const existing = transactions.find(t => t.shipmentId === shipment.id || t.title.includes(shipment.id));
    setActiveReceipt(existing ?? { id: `REC-${shipment.id}`, title: `Delivery · ${shipment.id}`, amount: -shipment.price, date: shipment.date, method: 'wallet', shipmentId: shipment.id, fee: 300, payer: name });
    openModal('receipt');
  };
  const confirmBooking = () => {
    if (paymentMethod === 'wallet' && balance < price) { setBookingError('Your wallet balance is too low. Add preview funds or choose the sample card.'); return; }
    paymentCommitted.current = false;
    setPendingPayment({ kind: 'delivery', amount: price, method: paymentMethod, payer: name, shipmentId: nextShipmentId(shipments), draft: {...draft} });
    openModal('payment-review');
  };
  const confirmPayment = () => {
    if (!pendingPayment || paymentCommitted.current) return;
    paymentCommitted.current = true;
    try {
      const result = recordPreviewPayment(balance, pendingPayment, `PAY-${crypto.randomUUID()}`, new Date());
      if (pendingPayment.kind === 'delivery' && pendingPayment.draft) {
        const d = pendingPayment.draft;
        const shipment: Shipment = { id: pendingPayment.shipmentId!, item: d.item, from: d.from, to: d.to, recipient: d.recipient, phone: d.phone, weight: d.weight, price: pendingPayment.amount, status: 'Booked', service: d.service, progress: 0, eta: d.when === 'Today' ? 'Pickup pending' : d.date, date: new Date().toLocaleDateString('en-GB'), instructions: d.instructions };
        setShipments(prev => [shipment, ...prev]); setSelected(shipment); go('tracking');
      }
      setBalance(result.balance); setTransactions(prev => [result.transaction, ...prev]);
      setActiveReceipt(result.transaction); setPendingPayment(null); setModal('payment-confirmed');
    } catch (error) {
      paymentCommitted.current = false;
      toast.error(error instanceof Error ? error.message : 'Payment could not be recorded. Please try again.');
    }
  };
  const sendMessage = (text = message) => {
    if (!text.trim()) return;
    const booking = draftFromText(text); const answer = assistantReply(text, shipments, booking, balance);
    setChat(prev => [...prev, { role: 'user', text }, { role: 'assistant', text: answer }]); setMessage(''); setAnnouncement(`Relay assistant: ${answer}`); if (booking) setPendingDraft(booking);
  };
  const currentTab = view === 'tracking' ? 'shipments' : view === 'booking' ? 'home' : view;
  const title = ({home: 'Home', shipments: 'My shipments', assistant: 'Relay AI', wallet: 'Your wallet', profile: 'Account', tracking: liveDetails ? 'Delivery status' : 'Tracking shipment', booking: 'New shipment'})[view];
  if (onboarding) return <div className={cn('intro-screen relay-intro visual-intro', zoomText && 'larger-text')}>
    <OriginalVideo className="intro-art" src="/video/relay-welcome-original.mp4" poster="/art/relay-start-4k.webp"/>
    <header className="intro-top"><span className="intro-brand"><span className="relay-mark"><Route aria-hidden="true" size={21}/></span>relay<span>.</span></span></header>
    <main className="intro-content"><h1 className="sr-only">Welcome to Relay delivery</h1><button className="get-started" onClick={() => { setOnboarding(false); setSignIn(true); }}><span className="start-parcel-seal"><Package aria-hidden="true" size={22}/></span><strong>Get Started</strong><span className="get-icon"><ChevronRight aria-hidden="true" size={22}/></span></button></main>
  </div>;

  const enterPreview = async () => {
    if (signInRequest.current) return;
    const controller = new AbortController();
    signInRequest.current = controller;
    setSignInError(''); setSigningIn(true);
    const timeout = setTimeout(() => controller.abort(), 10000);
    try {
      const response = await fetch('/api/preview-account', { cache: 'no-store', signal: controller.signal });
      if (!response.ok) throw new Error('Account request failed');
      const account = await response.json() as { mode?: string; name?: string; balance?: number; shipments?: Shipment[] };
      if (account.mode !== 'preview' || typeof account.name !== 'string' || !Number.isFinite(account.balance) || !Array.isArray(account.shipments) || !account.shipments.length || !account.shipments.every(isShipment)) throw new Error('Invalid account response');
      // Restore the browser's saved preview changes when present.
      let hasSavedPreview = false;
      try { hasSavedPreview = !!localStorage.getItem('relay-v1'); } catch { /* Continue in memory when browser storage is unavailable. */ }
      if (!hasSavedPreview) {
        setName(account.name); setBalance(account.balance!); setShipments(account.shipments!); setSelected(account.shipments![0]);
      }
      setSignIn(false); go('home');
    } catch {
      setSignInError('Your details could not load. Check your connection and try signing in again.');
    } finally {
      clearTimeout(timeout); signInRequest.current = null; setSigningIn(false);
    }
  };
  if (signingIn) return <main className={cn('app-shell sign-in-wait-screen', zoomText && 'larger-text')} >
    <div className="account-loading-mark" aria-hidden="true"><span className="account-loading-orbit"/><RelayAIMark size={80}/></div>
    <div className="sign-in-wait-status" role="status" aria-live="polite"><h1 id="sign-in-title" tabIndex={-1}>Loading your details…</h1><p>Preparing your delivery space.</p></div>
  </main>;
  if (signIn) return <div className={cn('app-shell preview-sign-in', zoomText && 'larger-text')}>
    <header className="sign-in-top"><button aria-label="Back to introduction" onClick={() => { signInRequest.current?.abort(); setSigningIn(false); setSignIn(false); setOnboarding(true); }}><ArrowLeft aria-hidden="true" size={20}/></button><span className="intro-brand"><span className="relay-mark"><Route aria-hidden="true" size={21}/></span>relay.</span></header>
    <main className="sign-in-main"><div className="sign-in-art"><Artwork kind="parcels"/><span className="sign-in-seal"><ShieldCheck aria-hidden="true" size={25}/></span></div><p className="eyebrow">YOUR DELIVERY SPACE</p><h1 id="sign-in-title" tabIndex={-1}>Welcome<br/>back.</h1><p className="sign-in-copy">Your deliveries, in one place.</p>
    <div className="auth-options"><Button variant="outline" className="google-sign-in" onClick={enterPreview}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img className="google-g" src="/art/google-g.png" width="20" height="20" alt=""/>Sign in with Google</Button><Button className="email-entry-button" onClick={enterPreview}><Mail aria-hidden="true" size={20}/>Continue with email<ChevronRight aria-hidden="true" size={18}/></Button></div>
    {signInError && <p id="sign-in-error" className="form-error" role="alert">{signInError}</p>}
    </main>
  </div>;

  return <div className={cn('app-shell', zoomText && 'larger-text')}>
    <div className="sr-only" role="status" aria-live="polite" aria-atomic="true">{announcement}</div>
    <a href="#main" className="skip-link">Skip to content</a>
    <div className="workspace"><header className="topbar">{view === 'home' ? <><button className="user-heading" onClick={() => go('profile')}><span className="avatar">{name.charAt(0)}</span><span><strong>{name}</strong><small><MapPin aria-hidden="true" size={12}/> Surulere, Lagos <ChevronRight aria-hidden="true" size={13}/></small></span></button><Button aria-label="Notifications" size="icon" variant="ghost" className="notification-button" onClick={() => openModal('notifications')}><Bell aria-hidden="true"/>{notify && <span className="notification-dot"/>}</Button></> : <><Button size="icon" variant="ghost" aria-label={view==='tracking'?'Back to shipments':'Back to home'} onClick={() => go(view==='tracking'?'shipments':'home')}><ArrowLeft aria-hidden="true"/></Button><h1 id="page-title" tabIndex={-1}>{title}</h1><Button size="icon" variant="ghost" aria-label="Help and support" onClick={() => openModal('support')}><HelpCircle aria-hidden="true"/></Button></>}</header><main id="main" className={cn('main', view === 'tracking' && 'tracking-page')} tabIndex={-1} key={view}>
    {view === 'home' && <>
    <div className="home-welcome"><p className="eyebrow">YOUR DELIVERY SPACE</p><h1 id="page-title" tabIndex={-1}>Keep good things<br/><span>moving.</span></h1><span className="shipment-count"><strong>{active.length.toString().padStart(2, '0')}</strong><small>on the move</small></span></div>
    <div className="home-actions"><button onClick={() => startBooking()}><span className="action-symbol"><Plus aria-hidden="true" size={24}/></span><span><strong>Send a parcel</strong><small>Start a new journey</small></span><ChevronRight aria-hidden="true" size={18}/></button><button onClick={() => openModal('find')}><span className="action-symbol"><Search aria-hidden="true" size={23}/></span><span><strong>Track</strong><small>Find an update</small></span></button></div>
    <div className="section-heading"><h2>On the move</h2><Button variant="ghost" onClick={() => go('shipments')}>All shipments <ChevronRight aria-hidden="true" size={15}/></Button></div>
    {active[0] ? <section className="current-card"><div className="current-card-top"><span className="parcel-icon"><Package aria-hidden="true" size={21}/></span><div><strong>{active[0].item}</strong><small>{active[0].id}</small></div><Badge className="status-badge">{active[0].status}</Badge></div><div className="delivery-moment"><span><small>{active[0].status === 'Booked' ? 'PICKUP' : 'ESTIMATED ARRIVAL'}</small><strong>{active[0].status === 'Booked' ? 'Pending' : active[0].eta}<em>{active[0].status === 'Booked' ? '' : ' min'}</em></strong><span>Every step, accounted for.</span></span><Artwork kind="parcels" className="current-parcels"/></div><ParcelProgress progress={active[0].progress}/><div className="current-route"><div><small>Collect from</small><strong>{active[0].from.split(',')[0]}</strong></div><span aria-hidden="true">→</span><div><small>Deliver to</small><strong>{active[0].to.split(',')[0]}</strong></div></div><Button className="detail-button" onClick={() => track(active[0])}>Follow this delivery <Navigation aria-hidden="true" size={16}/></Button></section> : <div className="empty-state"><Package aria-hidden="true" size={30}/><h2>Your next journey starts here.</h2><Button onClick={() => startBooking()}>Send a parcel</Button></div>}
    <button className="ai-home-strip" onClick={() => go('assistant')}><span className="spark-mark"><RelayAIMark aria-hidden="true" size={24}/></span><span><small>RELAY AI · PREVIEW</small><strong>Say it. We’ll help send it.</strong><span>Turn a simple request into a booking draft.</span></span><ChevronRight aria-hidden="true" size={20}/></button>
    <section className="home-balance"><div><small>Ready for your next delivery</small><button onClick={() => openModal('topup')}>Add funds <Plus aria-hidden="true" size={14}/></button></div><button className="balance-value" aria-label={`Open wallet, balance ${money(balance)}`} onClick={() => go('wallet')}>{money(balance)}<span>.00</span><Wallet aria-hidden="true" size={19}/></button><small>Available preview balance</small></section>
    <div className="section-heading"><h2>Recent journeys</h2><Button variant="ghost" onClick={() => go('shipments')}>See all <ChevronRight aria-hidden="true" size={15}/></Button></div><div className="shipment-list">{shipments.slice(0, 3).map(s => <ShipmentRow key={s.id} shipment={s} onClick={() => track(s)}/>)}</div>
    <section className="ship-showcase" aria-label="Relay logistics"><div className="showcase-caption"><p className="eyebrow">SMALL PARCELS. BIG POSSIBILITIES.</p><h2>Every journey<br/>means something.</h2></div><Artwork kind="ship" className="hero-ship"/></section><p className="preview-footnote">Sample deliveries · No real bookings or charges</p></>}

    {view === 'shipments' && <section className="full-panel"><div className="shipments-toolbar"><div className="search-input"><Search aria-hidden="true" size={19}/><Input aria-label="Search shipments" placeholder="Search package, location, or tracking ID" value={query} onChange={e => setQuery(e.target.value)}/></div><Button onClick={() => startBooking()}><Plus aria-hidden="true" data-icon="inline-start"/>New delivery</Button></div><ToggleGroup type="single" aria-label="Filter shipments by status" value={filter} onValueChange={v => v && setFilter(v)} className="filter-tabs"><ToggleGroupItem value="all">All shipments <span>{shipments.length}</span></ToggleGroupItem><ToggleGroupItem value="active">Active <span>{active.length}</span></ToggleGroupItem><ToggleGroupItem value="delivered">Delivered</ToggleGroupItem></ToggleGroup><p className="results-count" role="status" aria-live="polite">{visibleShipments.length} {visibleShipments.length === 1 ? 'shipment' : 'shipments'} found</p><div className="shipment-list">{visibleShipments.map(s => <ShipmentRow key={s.id} shipment={s} onClick={() => track(s)}/>)}{visibleShipments.length === 0 && <div className="empty-state"><Search aria-hidden="true" size={34}/><h2>No matching shipments</h2><p>Try another location or tracking ID.</p><Button variant="outline" onClick={() => { setQuery(''); setFilter('all'); }}>Clear filters</Button></div>}</div></section>}

    {view === 'tracking' && <div className={cn('tracking-layout', liveDetails && 'live-details')}><div className="tracking-map-wrap"><RouteMap key={selected.id} progress={selected.progress}/><div className="map-arrival"><span className="live-dot"/><span><small>{selected.status === 'In transit' ? 'Estimated arrival' : 'Latest update'}</small><strong>{selected.eta}{selected.status === 'In transit' && ' minutes'}</strong></span><Navigation aria-hidden="true" size={20}/></div></div><section className="tracking-sheet"><div className="rider-card"><span className="avatar rider-avatar">BA</span><div><strong>{selected.status === 'Booked' ? 'Finding your rider' : 'Babatunde Adeyemi'}</strong><span>{selected.status === 'Booked' ? 'Pickup pending' : 'Delivery partner'}</span></div><Button size="icon" variant="outline" aria-label="Message delivery partner" disabled={selected.status !== 'In transit'} onClick={() => openModal('rider')}><MessageCircle aria-hidden="true"/></Button><Button size="icon" className="rider-contact" aria-label="Delivery support" onClick={() => openModal('support')}><HelpCircle aria-hidden="true"/></Button></div><div className="tracking-id-row"><h2>{selected.id}</h2><Badge className="status-badge">{selected.status}</Badge></div><div className="tracking-package"><div className="route-addresses"><div><span className="route-node"/><span><small>Pickup</small><strong>{selected.from}</strong></span></div><div><span className="route-node orange"/><span><small>Delivery to {selected.recipient}</small><strong>{selected.to}</strong></span></div></div><Artwork kind="parcels"/></div><ParcelProgress progress={selected.progress}/><div className="tracking-summary"><span><small>Package</small><strong>{selected.item}</strong></span><span><small>Weight</small><strong>{selected.weight} kg</strong></span><span><small>Order cost</small><strong>{money(selected.price)}</strong></span><span><small>Arrival</small><strong>{selected.eta}{selected.status === 'In transit' && ' mins'}</strong></span></div><Button aria-expanded={liveDetails} aria-controls="journey-events" className="live-tracking-button" onClick={() => setLiveDetails(!liveDetails)}><span><Navigation aria-hidden="true" size={20}/></span>{liveDetails ? 'Hide journey updates' : 'Journey updates'}<ChevronRight aria-hidden="true" size={20}/></Button>
    {liveDetails && <div id="journey-events" className="delivery-details"><div className="delivery-status-banner"><Truck aria-hidden="true" size={26}/><span><strong>{selected.status === 'In transit' ? 'On its way' : selected.status}</strong><small>{selected.status === 'In transit' ? `Expected in ${selected.eta} minutes` : selected.eta}</small></span></div><h2>Delivery status</h2><ol className="timeline" aria-label="Delivery milestones">{['Booking confirmed', 'Picked up', 'On the way', 'Delivered'].map((label, i) => <li aria-current={i === selected.progress ? 'step' : undefined} key={label} className={cn('timeline-step', i <= selected.progress && 'complete')}><span>{i <= selected.progress ? <Check aria-hidden="true" size={12}/> : <span/>}</span><div><strong>{label}</strong><p>{i > selected.progress ? 'Coming up next' : i === selected.progress ? selected.status === 'Delivered' ? 'Received by recipient' : selected.status === 'Booked' ? 'Waiting for pickup' : 'Your package is on its way' : 'Sample delivery event'}</p></div></li>)}</ol><h2>Package details</h2><button className="tracking-copy" onClick={() => { if (!navigator.clipboard) { toast.error('Select and copy the tracking ID manually.'); return; } navigator.clipboard.writeText(selected.id).then(() => toast.success('Tracking ID copied')).catch(() => toast.error('Select and copy the tracking ID manually.')); }}><span><small>Tracking number</small><strong>{selected.id}</strong></span><Copy aria-hidden="true" size={18}/></button><div className="payment-method"><Wallet aria-hidden="true"/><div><strong>Payment status</strong><span>Recorded in preview · no bank charge</span></div><CheckCheck aria-hidden="true"/></div><div className="payment-method"><Leaf aria-hidden="true"/><div><strong>Shared route option</strong><span>Choose Eco for your next delivery</span></div><Button variant="ghost" onClick={() => { startBooking(); setDraft(prev => ({...prev, service: 'eco'})); }} aria-label="Book an Eco delivery"><ChevronRight aria-hidden="true"/></Button></div></div>}
    <div className="tracking-actions"><Button variant="outline" onClick={() => receipt(selected)}><ReceiptText aria-hidden="true" size={17}/>Receipt</Button><Button variant="outline" onClick={() => openModal('delivery-details')}>Package details</Button>{selected.status === 'Delivered' && <Button onClick={() => openModal('proof')}>Delivery proof</Button>}</div><p className="preview-footnote">Sample route and rider · No live GPS connection</p></section></div>}

    {view === 'booking' && <section className="booking-layout"><div className="booking-panel"><ol className="booking-progress" aria-label={`Booking progress, step ${step} of 3`}>{['Addresses', 'Package & service', 'Review & pay'].map((label, i) => <li aria-current={step === i + 1 ? 'step' : undefined} key={label} className={cn(step >= i + 1 && 'complete')}><span>{step > i + 1 ? <Check aria-hidden="true" size={15}/> : i + 1}</span><strong>{label}</strong></li>)}</ol><form key={step} className="booking-step-form" onSubmit={e => { e.preventDefault(); setBookingError(''); setInvalidField(null); if (step < 3) { if (step === 1) {
      if (draft.from.trim().length < 10) { failBooking('pickup', 'Enter a complete pickup address with a street, area, and city.'); return; }
      if (draft.to.trim().length < 10) { failBooking('destination', 'Enter a complete delivery address with a street, area, and city.'); return; }
      if (!draft.recipient.trim()) { failBooking('recipient', 'Enter the recipient’s name.'); return; }
      if (!/^(\+?234|0)[789][01]\d{8}$/.test(draft.phone.replace(/[\s-]/g, ''))) { failBooking('phone', 'Enter a valid Nigerian mobile number, such as 08012345678.'); return; }
    } if (step === 2) {
      if (!draft.item.trim()) { failBooking('item', 'Describe the package you are sending.'); return; }
      if (!Number.isFinite(draft.weight) || draft.weight < .1 || draft.weight > 50) { failBooking('weight', 'Enter a package weight between 0.1 and 50 kilograms.'); return; }
      if (draft.when === 'Schedule' && (!draft.date || draft.date < new Date().toLocaleDateString('en-CA'))) { failBooking('date', 'Choose today or a future date for pickup.'); return; }
    } setStep(step + 1); } else confirmBooking(); }}>
    {step === 1 && <><h2 id="booking-heading" tabIndex={-1}>Where’s it going?</h2><p className="muted-copy">We’ll collect at your door and deliver to theirs.</p><div className="saved-chips">{savedAddresses.map((address,i) => <Button key={`${address.label}-${address.address}-${i}`} type="button" variant="outline" onClick={() => updateDraft('from', address.address)}><Bookmark aria-hidden="true" data-icon="inline-start"/>{address.label}</Button>)}</div><FieldGroup><Field><FieldLabel htmlFor="pickup">Pickup address</FieldLabel><Input id="pickup" name="pickup" aria-invalid={invalidField === 'pickup'} aria-describedby={invalidField === 'pickup' ? 'booking-error' : undefined} required minLength={10} placeholder="Street, area, city" value={draft.from} onChange={e => updateDraft('from', e.target.value)} autoComplete="street-address"/></Field><Field><FieldLabel htmlFor="destination">Delivery address</FieldLabel><Input id="destination" name="destination" aria-invalid={invalidField === 'destination'} aria-describedby={invalidField === 'destination' ? 'booking-error' : undefined} required minLength={10} placeholder="Street, area, city" value={draft.to} onChange={e => updateDraft('to', e.target.value)}/></Field><div className="two-fields"><Field><FieldLabel htmlFor="recipient">Recipient’s name</FieldLabel><Input id="recipient" name="recipient" aria-invalid={invalidField === 'recipient'} aria-describedby={invalidField === 'recipient' ? 'booking-error' : undefined} required placeholder="Full name" value={draft.recipient} onChange={e => updateDraft('recipient', e.target.value)} autoComplete="name"/></Field><Field><FieldLabel htmlFor="phone">Recipient’s phone</FieldLabel><Input id="phone" name="phone" aria-invalid={invalidField === 'phone'} aria-describedby={invalidField === 'phone' ? 'booking-error' : undefined} required type="tel" placeholder="08012345678" value={draft.phone} onChange={e => updateDraft('phone', e.target.value)} autoComplete="tel"/></Field></div></FieldGroup></>}
    {step === 2 && <><h2 id="booking-heading" tabIndex={-1}>A little about your package.</h2><p className="muted-copy">Choose the delivery that fits your day.</p><FieldGroup><div className="two-fields"><Field><FieldLabel htmlFor="item">What are you sending?</FieldLabel><Input id="item" name="item" aria-invalid={invalidField === 'item'} aria-describedby={invalidField === 'item' ? 'booking-error' : undefined} required placeholder="e.g. Documents, clothing" value={draft.item} onChange={e => updateDraft('item', e.target.value)}/></Field><Field><FieldLabel htmlFor="weight">Weight in kg</FieldLabel><Input id="weight" name="weight" aria-invalid={invalidField === 'weight'} aria-describedby={invalidField === 'weight' ? 'booking-error' : undefined} type="number" min="0.1" max="50" step="0.1" required value={draft.weight} onChange={e => updateDraft('weight', Number(e.target.value))}/></Field></div><Field><FieldLabel>Delivery service</FieldLabel><ToggleGroup type="single" aria-label="Delivery service" value={draft.service} onValueChange={v => v && updateDraft('service', v)} className="service-options">{[{ id: 'standard', name: 'Standard', icon: Bike, description: 'Same day · lower cost' }, { id: 'express', name: 'Express', icon: Zap, description: 'Priority · 1–2 hours' }, { id: 'eco', name: 'Eco', icon: Leaf, description: 'Next day · shared route' }].map(s => <ToggleGroupItem key={s.id} value={s.id}><s.icon aria-hidden="true" size={23}/><strong>{s.name}</strong><small>{s.description}</small><b>{money(servicePrice(s.id, draft.weight))}</b></ToggleGroupItem>)}</ToggleGroup><FieldDescription>Illustrative prices for local deliveries. Final coverage and pricing need a courier connection.</FieldDescription></Field><Field><FieldLabel>Pickup time</FieldLabel><ToggleGroup type="single" aria-label="Pickup time" value={draft.when} onValueChange={v => v && updateDraft('when', v)} className="filter-tabs"><ToggleGroupItem value="Today">Today</ToggleGroupItem><ToggleGroupItem value="Schedule">Schedule pickup</ToggleGroupItem></ToggleGroup></Field>{draft.when === 'Schedule' && <Field><FieldLabel htmlFor="date">Pickup date</FieldLabel><Input id="date" name="date" aria-invalid={invalidField === 'date'} aria-describedby={invalidField === 'date' ? 'booking-error' : undefined} type="date" required min={new Date().toLocaleDateString('en-CA')} value={draft.date} onChange={e => updateDraft('date', e.target.value)}/></Field>}<Field><FieldLabel htmlFor="instructions">Delivery instructions <span className="muted">(optional)</span></FieldLabel><Input id="instructions" placeholder="e.g. Call on arrival, handle with care" value={draft.instructions} onChange={e => updateDraft('instructions', e.target.value)}/></Field></FieldGroup></>}
    {step === 3 && <><h2 id="booking-heading" tabIndex={-1}>Everything look right?</h2><p className="muted-copy">Review your delivery before confirming.</p><div className="review-address"><span><MapPin aria-hidden="true" size={21}/><div><small>Collect from</small><strong>{draft.from}</strong></div></span><span><Navigation aria-hidden="true" size={21}/><div><small>Deliver to</small><strong>{draft.to}</strong><p>{draft.recipient} · {draft.phone}</p></div></span></div><div className="review-table"><div><span>Package</span><strong>{draft.item} · {draft.weight} kg</strong></div><div><span>Service</span><strong className="capitalize">{draft.service}</strong></div><div><span>Pickup</span><strong>{draft.when === 'Today' ? 'Today' : draft.date}</strong></div>{draft.instructions && <div><span>Instructions</span><strong>{draft.instructions}</strong></div>}<div><span>Delivery</span><strong>{money(price - 300)}</strong></div><div><span>Handling & protection</span><strong>₦300</strong></div><div className="total"><span>Total</span><strong>{money(price)}</strong></div></div><Field className="booking-payment-choice"><FieldLabel>How would you like to pay?</FieldLabel><ToggleGroup type="single" value={paymentMethod} onValueChange={v=>v&&setPaymentMethod(v as PaymentMethod)} aria-label="Payment method" className="payment-choice"><ToggleGroupItem value="wallet"><Wallet aria-hidden="true" size={22}/><span><strong>Relay wallet</strong><small>{money(balance)} preview balance</small></span><CircleCheck aria-hidden="true" size={18}/></ToggleGroupItem><ToggleGroupItem value="sample-card"><CreditCard aria-hidden="true" size={22}/><span><strong>Sample card</strong><small>Visa · 4242 · No bank charge</small></span><CircleCheck aria-hidden="true" size={18}/></ToggleGroupItem></ToggleGroup></Field><p className="preview-footnote">You’ll review the payment before confirming. No real funds will move.</p></>}
    {bookingError && <div id="booking-error" role="alert" className="form-error">{bookingError}{balance < price && step === 3 && <Button type="button" variant="outline" onClick={() => openModal('topup')}>Add preview funds</Button>}</div>}<div className="form-actions">{step > 1 && <Button variant="outline" type="button" onClick={() => { setStep(step - 1); setBookingError(''); }}>Back</Button>}<Button type="submit">{step === 3 ? `Review payment · ${money(price)}` : 'Continue'}</Button></div></form></div><aside className="booking-aside"><span className="spark-mark"><RelayAIMark aria-hidden="true" size={25}/></span><h2>Skip the typing.</h2><p>Describe your delivery to Relay AI and start with a prepared draft.</p><Button variant="outline" onClick={() => go('assistant')}>Try the assistant</Button><div className="care-note"><ShieldCheck aria-hidden="true" size={24}/><p>Review every detail before any booking is confirmed.</p></div></aside></section>}

    {view === 'assistant' && <div className="ai-layout"><section className="chat-panel"><div className="chat-header"><span className="spark-mark"><RelayAIMark aria-hidden="true" size={24}/></span><div><h2>Relay AI</h2><p>Try tracking, quotes and booking drafts</p></div><Badge variant="outline">Preview AI</Badge></div><MessageScrollerProvider><MessageScroller className="chat-scroll"><MessageScrollerViewport aria-label="Conversation with Relay assistant" tabIndex={0}><MessageScrollerContent className="chat-content">{chat.map((m, i) => <Message key={i} className={i===chat.length-1?"message-new":undefined} align={m.role === 'user' ? 'end' : 'start'}><MessageContent><span className="sr-only">{m.role === 'user' ? 'You: ' : 'Relay assistant: '}</span><Bubble variant={m.role === 'user' ? 'default' : 'secondary'}><BubbleContent>{m.text}</BubbleContent></Bubble></MessageContent></Message>)}</MessageScrollerContent></MessageScrollerViewport></MessageScroller></MessageScrollerProvider>{pendingDraft && <div className="draft-result"><span><Package aria-hidden="true" size={21}/><strong>Your booking draft is ready</strong></span><p>{pendingDraft.from} → {pendingDraft.to}</p><Button onClick={() => startBooking(pendingDraft)}>Review booking draft</Button></div>}<div className="chat-suggestions">{['Where is my package?', 'Compare delivery options', 'Summarize my deliveries', 'Send documents from Lekki to Ikeja tomorrow'].map(t => <button key={t} onClick={() => sendMessage(t)}>{t}</button>)}</div><form className="chat-composer" onSubmit={e => { e.preventDefault(); sendMessage(); }}><Input aria-label="Message Relay AI" enterKeyHint="send" placeholder="Tell me what you need delivered…" value={message} onChange={e => setMessage(e.target.value)}/><Button type="submit" size="icon" aria-label="Send message" disabled={!message.trim()}><Send aria-hidden="true"/></Button></form><p className="chat-disclaimer">Interactive preview AI · Uses your saved sample data and guided responses. No live model connected.</p></section><aside className="ai-guide"><h2>Less admin.<br/>More moving.</h2><p>Start with a simple request.</p><button className="example-request" onClick={() => sendMessage('Send documents from Lekki to Ikeja tomorrow')}><span>TRY SAYING</span><strong>“Send documents from Lekki to Ikeja tomorrow.”</strong><Send aria-hidden="true" size={19}/></button><div className="ai-capability"><Package aria-hidden="true"/><span><strong>Prepare a booking</strong><p>Turn your request into an editable draft.</p></span></div><div className="ai-capability"><Clock3 aria-hidden="true"/><span><strong>Understand an update</strong><p>Check the latest saved shipment status.</p></span></div><div className="ai-capability"><SlidersHorizontal aria-hidden="true"/><span><strong>Choose your service</strong><p>Compare cost, speed, and flexibility.</p></span></div></aside></div>}

    {view === 'wallet' && <div className="wallet-grid"><section><div className="balance-card"><Wallet aria-hidden="true" size={25}/><p>Available balance</p><h2>{money(balance)}</h2><div className="balance-bottom"><span>NGN · Nigerian naira</span><Button className="light-button" onClick={() => openModal('topup')}><Plus aria-hidden="true" data-icon="inline-start"/>Add funds</Button></div></div><div className="section-heading transaction-heading"><h2>Activity</h2><Badge variant="outline">Receipts</Badge></div><div className="transaction-list">{transactions.length===0&&<div className="empty-state"><ReceiptText aria-hidden="true" size={30}/><h2>Your receipts belong here.</h2><p>Add preview funds or book a delivery to see your first receipt.</p></div>}{transactions.map(t => <button className="transaction transaction-button" key={t.id} onClick={()=>{setActiveReceipt(t);openModal('receipt');}} aria-label={`View receipt for ${t.title}, ${money(Math.abs(t.amount))}`}><span className={cn('transaction-icon', t.amount > 0 && 'credit')}>{t.amount > 0 ? <Plus aria-hidden="true" size={21}/> : <Package aria-hidden="true" size={21}/>}</span><span><strong>{t.title}</strong><small>{t.date}</small></span><strong className={cn(t.amount > 0 && 'positive')}>{t.amount > 0 ? '+' : '−'}{money(Math.abs(t.amount))}</strong><ReceiptText aria-hidden="true" size={18}/></button>)}</div></section><aside><div className="wallet-explainer"><ShieldCheck aria-hidden="true" size={30}/><h2>One wallet.<br/>Fewer interruptions.</h2><p>Book deliveries using your balance and keep every receipt in one place.</p><Button variant="outline" onClick={() => { if(transactions[0]) {setActiveReceipt(transactions[0]);openModal('receipt');} else toast.info('Your receipts will appear after your first payment.'); }}>View latest receipt</Button></div><p className="preview-footnote">No payment processor is connected. Funds and transactions exist only in this browser’s preview.</p></aside></div>}

    {view === 'profile' && <div className="profile-grid"><section className="profile-panel"><div className="profile-header"><span className="avatar large-avatar">{name.charAt(0)}</span><h2>{name}</h2><p>Personal delivery account</p><Badge variant="outline">Preview account</Badge></div><div className="account-links"><button onClick={() => openModal('edit-profile')}><UserRound aria-hidden="true"/><span>Personal details</span><ChevronRight aria-hidden="true"/></button><button onClick={() => openModal('addresses')}><Bookmark aria-hidden="true"/><span>Saved addresses</span><small>{savedAddresses.length}</small><ChevronRight aria-hidden="true"/></button><button onClick={() => openModal('preferences')}><Settings2 aria-hidden="true"/><span>Preferences</span><ChevronRight aria-hidden="true"/></button><button onClick={() => openModal('support')}><HelpCircle aria-hidden="true"/><span>Help & support</span><ChevronRight aria-hidden="true"/></button><button onClick={() => { setSignIn(true); go('home'); }}><LogOut aria-hidden="true"/><span>Sign out</span><ChevronRight aria-hidden="true"/></button><button onClick={() => openModal('reset')}><RotateCcw aria-hidden="true"/><span>Reset saved data</span><ChevronRight aria-hidden="true"/></button></div></section><aside className="profile-note"><h2>A delivery experience<br/>that remembers you.</h2><p>Save your regular addresses, choose your preferences, and spend less time filling forms.</p><div className="care-note"><ShieldCheck aria-hidden="true" size={25}/><p>Preview data is saved on this device. No real account has been created.</p></div></aside></div>}
    </main><nav className="bottom-nav" aria-label="Mobile navigation">{tabs.map(tab => <button key={tab.id} aria-label={tab.label} className={cn(currentTab === tab.id && 'selected')} aria-current={currentTab === tab.id ? 'page' : undefined} onClick={() => go(tab.id)}><tab.icon aria-hidden="true" size={22}/><span>{tab.label}</span></button>)}</nav></div>

    <Dialog open={!!modal} onOpenChange={open => !open && setModal(null)}><DialogContent className={cn("relay-dialog", zoomText && "larger-text", modal === "payment-confirmed" && "payment-complete")} onCloseAutoFocus={event => { event.preventDefault(); const target = dialogReturnFocus.current; if (target?.isConnected) target.focus(); else document.getElementById('page-title')?.focus(); }}><DialogHeader><DialogTitle id="relay-dialog-title" tabIndex={-1}>{({ notifications: 'Your updates', topup: 'Add funds', receipt: 'Your receipt', 'payment-review': 'Review payment', 'payment-confirmed': 'Payment confirmation', 'card-info': 'Card payments', success: 'Your delivery is booked.', find: 'Track a parcel', rider: 'Message your rider', 'delivery-details': 'Package details', proof: 'Proof of delivery', support: 'How can we help?', addresses: 'Your saved addresses', preferences: 'Your preferences', 'edit-profile': 'Personal details', reset: 'Start a fresh preview?' } as Record<string, string>)[modal ?? ''] ?? 'Relay'}</DialogTitle><DialogDescription>{modal === 'payment-review' ? 'Check the amount and method. This preview moves no real money.' : modal === 'payment-confirmed' || modal === 'receipt' ? 'A record of your local preview payment.' : modal === 'card-info' ? 'Card information and availability.' : modal === 'success' ? 'Your preview booking is saved. No real courier has been requested.' : modal === 'topup' ? 'Explore wallet payments without making a real payment.' : modal === 'rider' ? 'Preview conversation. Messages are saved locally and not sent to a rider.' : modal === 'proof' ? 'Sample confirmation for this completed delivery.' : modal === 'support' ? 'Get help with booking, tracking, and your preview.' : modal === 'reset' ? 'This removes your preview bookings, funds, and saved preferences on this device.' : 'Manage your Relay preview.'}</DialogDescription></DialogHeader>
    {modal === 'notifications' && <div className="notification-list">{!notify ? <p className="muted-copy">Sample updates are turned off. Enable them in Account preferences.</p> : shipments.length === 0 ? <p className="muted-copy">No delivery updates yet. Create a preview shipment to get started.</p> : shipments.slice(0,3).map(shipment => <div key={shipment.id}><span className="parcel-icon"><Truck aria-hidden="true"/></span><span><strong>{shipment.item} · {shipment.status}</strong><p>{shipment.id} · Saved preview update</p><Button variant="outline" onClick={() => { setModal(null); track(shipment); }}>View delivery</Button></span></div>)}</div>}
    {modal === 'topup' && <form onSubmit={e => { e.preventDefault(); const amount = Number(topup); if (!Number.isFinite(amount) || amount < 100 || amount > 1000000) { toast.error('Enter an amount between ₦100 and ₦1,000,000.'); return; } paymentCommitted.current = false; setPendingPayment({kind:'topup',amount,method:'sample-card',payer:name}); setModal('payment-review'); }}><FieldGroup><Field><FieldLabel htmlFor="topup">Amount in naira</FieldLabel><Input id="topup" type="number" min="100" max="1000000" step="1" required value={topup} onChange={e => setTopup(e.target.value)}/></Field><ToggleGroup type="single" aria-label="Suggested top-up amounts" value={topup} onValueChange={v => v && setTopup(v)} className="filter-tabs">{['5000', '10000', '20000'].map(v => <ToggleGroupItem key={v} value={v}>{money(Number(v))}</ToggleGroupItem>)}</ToggleGroup><button type="button" className="payment-card-option" onClick={()=>setModal('card-info')}><CreditCard aria-hidden="true" size={23}/><span><strong>Sample Visa · 4242</strong><small>Preview card · no bank charge</small></span><ChevronRight aria-hidden="true" size={18}/></button><p className="preview-footnote">Real card payments aren’t connected. No card number or security code is required.</p><Button type="submit">Review top-up<ChevronRight aria-hidden="true" size={18}/></Button></FieldGroup></form>}
    {modal === 'card-info' && <div className="card-availability"><div className="sample-bank-card"><span>RELAY / VISA</span><CreditCard aria-hidden="true" size={30}/><strong>•••• •••• •••• 4242</strong><small>SAMPLE CARD · NO BANK CHARGE</small></div><h3>Your card details stay private.</h3><p>No real card is saved or charged. This sample card lets you explore the payment and receipt flow. Real payments require a connected payment provider.</p><Button onClick={()=>setModal('topup')}>Back to add funds</Button></div>}
    {modal === 'payment-review' && pendingPayment && <div className="payment-review"><span className="payment-review-icon"><ReceiptText aria-hidden="true" size={28}/></span><p className="eyebrow">YOU’RE ABOUT TO {pendingPayment.kind==='topup'?'ADD FUNDS':'PAY FOR A DELIVERY'}</p><h2>{money(pendingPayment.amount)}</h2><div className="review-table"><div><span>For</span><strong>{pendingPayment.kind==='topup'?'Wallet top-up':pendingPayment.draft?.item}</strong></div><div><span>Payment method</span><strong>{paymentMethodLabel(pendingPayment.method)}</strong></div>{pendingPayment.shipmentId&&<div><span>Shipment</span><strong>{pendingPayment.shipmentId}</strong></div>}<div><span>Amount</span><strong>{money(pendingPayment.amount-(pendingPayment.kind==='delivery'?300:0))}</strong></div><div><span>Fees</span><strong>{pendingPayment.kind==='delivery'?'₦300':'₦0'}</strong></div><div className="total"><span>Total</span><strong>{money(pendingPayment.amount)}</strong></div></div><p className="payment-preview-notice"><ShieldCheck aria-hidden="true" size={18}/>Preview payment. No bank charge or real money transfer.</p><Button className="confirm-payment-button" onClick={confirmPayment}>Confirm preview payment · {money(pendingPayment.amount)}</Button><Button variant="outline" onClick={()=>{setPendingPayment(null);setModal(pendingPayment.kind==='topup'?'topup':null);}}>Back to edit</Button></div>}
    {(modal === 'receipt' || modal === 'payment-confirmed') && activeReceipt && <><PaymentReceipt transaction={activeReceipt} payer={name}/>{modal==='payment-confirmed'&&<Button className="payment-done-button" onClick={()=>setModal(null)}>Done<Check aria-hidden="true" size={18}/></Button>}</>}
    {modal === 'success' && <div className="success-content"><span className="success-check"><Check aria-hidden="true" size={38}/></span><strong>{selected.id}</strong><p>{selected.from} → {selected.to}</p><Button onClick={() => { setModal(null); go('tracking'); }}>View delivery</Button><Button variant="outline" onClick={() => { setModal(null); go('home'); }}>Back home</Button></div>}
    {modal === 'find' && <form onSubmit={e => { e.preventDefault(); const match = shipments.find(s => s.id.toLowerCase() === trackingInput.trim().toLowerCase()); if (!match) { toast.error('No matching parcel. Try RLY-20841 or an ID from your Shipments.'); return; } setModal(null); track(match); }}><FieldGroup><Field><FieldLabel htmlFor="trackingid">Tracking ID</FieldLabel><Input id="trackingid" autoCapitalize="characters" autoCorrect="off" placeholder="e.g. RLY-20841" value={trackingInput} onChange={e => setTrackingInput(e.target.value)} required/></Field><Button type="submit"><Search aria-hidden="true" data-icon="inline-start"/>Find parcel</Button></FieldGroup></form>}
    {modal === 'rider' && <div><div className="rider-preview"><p>Hi! Your sample package is on its way. You can leave an arrival instruction below.</p>{riderMessages.map((m, i) => <p className="rider-local-message" key={i}>{m}<small>Saved in preview</small></p>)}</div><form className="chat-composer" onSubmit={e => { e.preventDefault(); if (riderMessage.trim()) { setRiderMessages(prev => [...prev, riderMessage]); setRiderMessage(''); toast.success('Message saved in preview only'); } }}><Input aria-label="Arrival instruction" placeholder="Your arrival instruction…" value={riderMessage} onChange={e => setRiderMessage(e.target.value)}/><Button size="icon" type="submit" disabled={!riderMessage.trim()} aria-label="Save preview message"><Send aria-hidden="true"/></Button></form></div>}
    {modal === 'delivery-details' && <div className="review-table"><div><span>Tracking ID</span><strong>{selected.id}</strong></div><div><span>Package</span><strong>{selected.item}</strong></div><div><span>Weight</span><strong>{selected.weight} kg</strong></div><div><span>Service</span><strong className="capitalize">{selected.service}</strong></div><div><span>Recipient</span><strong>{selected.recipient}</strong></div><div><span>Instructions</span><strong>{selected.instructions || 'No special instructions'}</strong></div><div className="total"><span>Total</span><strong>{money(selected.price)}</strong></div></div>}
    {modal === 'proof' && <div className="proof-panel"><ShieldCheck aria-hidden="true" size={42}/><h3>Received by {selected.recipient}</h3><p>Confirmation code: 4829</p><p>Sample handoff confirmed · {selected.date}</p><Button variant="outline" onClick={() => receipt(selected)}><Download aria-hidden="true" data-icon="inline-start"/>View receipt</Button></div>}
    {modal === 'support' && <div className="support-options"><button onClick={() => { setModal(null); go('assistant'); sendMessage('How do I book a delivery?'); }}><Package aria-hidden="true"/><span><strong>Booking help</strong><small>Addresses, packages, and services</small></span><ChevronRight aria-hidden="true"/></button><button onClick={() => { setModal(null); go('assistant'); sendMessage('Where is my package?'); }}><MapPin aria-hidden="true"/><span><strong>Tracking help</strong><small>Understand your delivery update</small></span><ChevronRight aria-hidden="true"/></button><p className="muted-copy">This preview has no live support team connected.</p></div>}
    {modal === 'addresses' && <div className="address-modal">{savedAddresses.map((a, i) => <div key={i}><Bookmark aria-hidden="true" size={21}/><span><strong>{a.label}</strong><p>{a.address}</p></span><Button size="icon" variant="ghost" aria-label={`Delete ${a.label} address`} onClick={() => setSavedAddresses(prev => prev.filter((_, idx) => idx !== i))}><X aria-hidden="true"/></Button></div>)}<form onSubmit={e => { e.preventDefault(); if (!addressLabel.trim() || newAddress.trim().length < 5) { setAddressError('Add a label and a complete street address before saving.'); document.getElementById(!addressLabel.trim()?'address-label':'new-address')?.focus(); return; } setAddressError(''); setSavedAddresses(prev => [...prev, { label: addressLabel.trim(), address: newAddress.trim() }]); setNewAddress(''); setAddressLabel(''); toast.success('Address saved'); }}><FieldGroup><Field><FieldLabel htmlFor="address-label">Label</FieldLabel><Input id="address-label" aria-invalid={!!addressError && !addressLabel.trim()} aria-describedby={addressError?"address-error":undefined} placeholder="e.g. Studio" required value={addressLabel} onChange={e => setAddressLabel(e.target.value)}/></Field><Field><FieldLabel htmlFor="new-address">Address</FieldLabel><Input id="new-address" aria-invalid={!!addressError && newAddress.trim().length < 5} aria-describedby={addressError?"address-error":undefined} placeholder="Street, area, city" required minLength={5} value={newAddress} onChange={e => setNewAddress(e.target.value)}/></Field>{addressError&&<p id="address-error" className="form-error" role="alert">{addressError}</p>}<Button type="submit"><Plus aria-hidden="true" data-icon="inline-start"/>Save address</Button></FieldGroup></form></div>}
    {modal === 'preferences' && <div className="preferences"><div><label htmlFor="notify"><strong>Delivery notifications</strong><p>Enable sample updates in this preview.</p></label><Switch id="notify" checked={notify} onCheckedChange={setNotify}/></div><div><label htmlFor="larger"><strong>Larger text</strong><p>Increase text size across the app.</p></label><Switch id="larger" checked={zoomText} onCheckedChange={setZoomText}/></div></div>}
    {modal === 'edit-profile' && <form onSubmit={e => { e.preventDefault(); if (!profileName.trim()) { setProfileError('Enter your name before saving.'); document.getElementById('name')?.focus(); return; } setName(profileName.trim()); setModal(null); toast.success('Profile saved on this device'); }}><FieldGroup><Field><FieldLabel htmlFor="name">Full name</FieldLabel><Input id="name" required minLength={1} value={profileName} aria-invalid={!!profileError} aria-describedby={profileError?'profile-error':undefined} onChange={e => {setProfileName(e.target.value);setProfileError('');}}/>{profileError&&<p className="form-error" id="profile-error" role="alert">{profileError}</p>}</Field><Button type="submit">Save details</Button><Button type="button" variant="outline" onClick={()=>setModal(null)}>Cancel</Button></FieldGroup></form>}
    {modal === 'reset' && <><Button variant="destructive" onClick={() => { try { localStorage.removeItem('relay-v1'); location.reload(); } catch { toast.error('Your browser blocked the reset. Allow site storage and try again.'); } }}>Reset saved data</Button><Button variant="outline" onClick={() => setModal(null)}>Keep exploring</Button></>}
    </DialogContent></Dialog>
  </div>;
}
